/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_hydos_fabriclangc_bridge_CBridge */

#ifndef _Included_io_github_hydos_fabriclangc_bridge_CBridge
#define _Included_io_github_hydos_fabriclangc_bridge_CBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_hydos_fabriclangc_bridge_CBridge
 * Method:    parseJniEnv
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_io_github_hydos_fabriclangc_bridge_CBridge_parseJniEnv
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     io_github_hydos_fabriclangc_bridge_CBridge
 * Method:    passToNative
 * Signature: (JLjava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_io_github_hydos_fabriclangc_bridge_CBridge_passToNative
  (JNIEnv *, jclass, jlong, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
